config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subjects do
    resources :comments, shallow: true
  end
  resources :users
  resources :beasts do
    resources :comments, shallow: true
  end

  root 'main#index'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :beast, optional: true
  belongs_to :subject, optional: true

  validates :rate, presence: true, inclusion: {in: 1..10}
  validate :obscenity_validator

  def obscenity_validator
    errors.add(:message, "should not contain swearwords") if Obscenity.profane?(message)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource


  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json

  def create
    if params[:beast_id] # add comment to beast
      @beast = Beast.find(params[:beast_id])
      @comment = @beast.comments.new(comment_params)
      @comment.user_id = current_user.id

      @new_rating = (@beast.comments.count * @beast.rating + @comment.rate) / (@beast.comments.count + 1)

      respond_to do |format|
        if @comment.save
          @beast.rating = @new_rating
          @beast.save
          format.html { redirect_to @beast, notice: 'Komentarz został dodany' }
        else
          format.html { redirect_to @beast, alert: 'Komentarz NIE może zawierać przekleństw!' }
        end
      end

    elsif params[:subject_id] # add comment to subject
      @subject = Subject.find(params[:subject_id])
      @comment = @subject.comments.new(comment_params)
      @comment.user_id = current_user.id

      @new_rating = (@subject.comments.count * @subject.rating + @comment.rate) / (@subject.comments.count + 1)

      respond_to do |format|
        if @comment.save
          @subject.rating = @new_rating
          @subject.save
          format.html { redirect_to @subject, notice: 'Komentarz został dodany' }
        else
          format.html { redirect_to @subject, alert: 'Komentarz NIE może zawierać przekleństw!' }
        end
      end
    end
  end


  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @new_comment_rate = comment_params.fetch(:rate).to_i
    if @comment.beast_id
      @beast = @comment.beast
      @new_rating = (@beast.comments.count * @beast.rating - @comment.rate + @new_comment_rate) / (@beast.comments.count)

      respond_to do |format|
        if @comment.update(comment_params)
          @beast.rating = @new_rating
          @beast.save
          format.html { redirect_to @beast, notice: 'Zmiany zostały zapisane' }
        else
          format.html { render :edit }
        end
      end
    else
      @subject = @comment.subject
      @new_rating = (@subject.comments.count * @subject.rating - @comment.rate.to_i + @new_comment_rate) / (@subject.comments.count)

      respond_to do |format|
        if @comment.update(comment_params)
          @subject.rating = @new_rating
          @subject.save
          format.html { redirect_to @subject, notice: 'Zmiany zostały zapisane' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    if @comment.beast_id
      @beast = @comment.beast
      @new_rating = (@beast.comments.count * @beast.rating - @comment.rate) / (@beast.comments.count - 1)
      @beast.rating = @new_rating >= 0 ? @new_rating : 0
      @beast.save
    else
      @subject = @comment.subject
      @new_rating = (@subject.comments.count * @subject.rating - @comment.rate) / (@subject.comments.count - 1)
      @subject.rating = @new_rating >= 0 ? @new_rating : 0
      @subject.save
    end

    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @beast || @subject, notice: 'Komentarz został usunięty' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:rate, :message, :user_id, :beast_id, :subject_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rate %>
    <%= form.text_field :rate %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edycja komentarza</h1>

<%= render 'form', comment: @comment %>

<% if @comment.beast%>
  <%= link_to "wróc do bestii", @comment.beast %>
<% else %>
  <%= link_to "wróc do przedmiotu", @comment.subject %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Rate</th>
      <th>Message</th>
      <th>User</th>
      <th>Beast</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.rate %></td>
        <td><%= comment.message %></td>
        <td><%= comment.user %></td>
        <td><%= comment.beast %></td>
        <td><%= comment.subject %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
  <div class="d-flex w-100 justify-content-between">
    <h5 class="mb-1"> <%= @comment.rate %></h5>
    <small class="text-muted">  <%= @comment.user %></small>
  </div>
  <p class="mb-1"><%= @comment.message %></p>
  <small class="text-muted"><%= @comment.subject %></small>
</a>