config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subjects do
    resources :comments, shallow: true
  end
  resources :users
  resources :beasts do
    resources :comments, shallow: true
  end

  root 'main#index'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments

  after_create :set_sub

  validates :displayname, presence: true, length: {minimum: 2, maximum: 255}
  validates :firstname, presence: true, length: {minimum: 2, maximum: 255}
  validates :lastname, presence: true, length: {minimum: 2, maximum: 255}

  def set_sub
    self.role = :client
  end

  def client?
    self.role == "client"
  end

  def admin?
    self.role == "admin"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Użytkownik został stworzony' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Zmiany zostały zapisane' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Użytkownik został usunięty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :displayname, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Wystąpiły następujące błędy</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-8">
      <%= form.label :imię %><br>
      <%= form.text_field :firstname, id: :user_firstname %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-8">
      <%= form.label :nazwisko %><br>
      <%= form.text_field :lastname, id: :user_lastname %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-8">
      <%= form.label :login %><br>
      <%= form.text_field :displayname, id: :user_displayname %>
    </div>
  </div>

  <% if current_user.role == "admin" %>
    <div class="row">
      <div class="form-group col-md-8">
      <%= form.label :rol %>
        <%= form.select :role, options_for_select(['admin', 'client']), id: :user_role %>
    </div>
    </div>
  <% end %>

  <div class="actions">
    <%= form.button :submit, "Zapisz" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edytowanie użytkownika</h1>

<%= render 'form', user: @user %>


<hr class="my-4">


<%= link_to 'Pokaż', @user %> |
<%= link_to 'Powrót', users_path %>

app/views/users/index.html.erb
<h1>Użytkownicy</h1>

<table class="table">
  <thead>
    <tr>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>Login</th>
      <th>Rola</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.displayname %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Pokaż', user %></td>
        <td><%= link_to 'Edytuj', edit_user_path(user) %></td>
        <td><%= link_to 'Usuń', user, method: :delete, data: { confirm: 'Na pewno chcesz usunąć tego użytkownika?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Nowy użytkownik</h1>

<%= render 'form', user: @user %>


<hr class="my-4">

<%= link_to 'Powrót', users_path %>

app/views/users/show.html.erb
<% if notice %>
  <div class="alert alert-success">
    <div class="notice">
      <%= notice %>
    </div>
  </div>
<% end %>



<div class="jumbotron">
  <h1 class="display-3"> ( <%= @user.displayname %> )</h1>
  <h3><%= @user.firstname %> <%= @user.lastname %></h3>
  <hr class="my-4">
  <h3>Rola: <%= @user.role %> </h3>

</div>



<hr class="my-4">


<%= link_to 'Edytuj', edit_user_path(@user) %> |
<%= link_to 'Powrót', users_path %>