config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subjects do
    resources :comments, shallow: true
  end
  resources :users
  resources :beasts do
    resources :comments, shallow: true
  end

  root 'main#index'

end

app/models/beast.rb
class Beast < ApplicationRecord
  has_many :comments
  has_and_belongs_to_many :subjects
  has_one_attached :image


  validates :firstname, presence: true, length: {minimum: 2, maximum: 255}
  validates :lastname, presence: true, length: {minimum: 2, maximum: 255}
  validates :degree, presence: true
  validates :image, file_content_type: { allow: ['image/jpeg', 'image/png'] }

  def to_label
    "#{firstname} #{lastname}"
  end

end

app/controllers/beasts_controller.rb
class BeastsController < ApplicationController
  before_action :set_beast, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource


  # GET /beasts
  # GET /beasts.json
  def index
    @beasts = Beast.all
  end

  # GET /beasts/1
  # GET /beasts/1.json
  def show
  end

  # GET /beasts/new
  def new
    @beast = Beast.new
  end

  # GET /beasts/1/edit
  def edit
  end

  # POST /beasts
  # POST /beasts.json
  def create
    @beast = Beast.new(beast_params)
    @beast.rating = 0

    unless @beast.image.attached?
      @beast.image.attach(io: File.open(Rails.root.join('av.jpg')), filename: 'av.jpg')
    end


    respond_to do |format|
      if @beast.save
        format.html { redirect_to @beast, notice: 'Bestia została dodana do Bestiariusza' }
        format.json { render :show, status: :created, location: @beast }
      else
        format.html { render :new }
        format.json { render json: @beast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beasts/1
  # PATCH/PUT /beasts/1.json
  def update
    respond_to do |format|
      if @beast.update(beast_params)
        format.html { redirect_to @beast, notice: 'Dane bestii zostały zaktualizowane' }
        format.json { render :show, status: :ok, location: @beast }
      else
        format.html { render :edit }
        format.json { render json: @beast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beasts/1
  # DELETE /beasts/1.json
  def destroy
    @beast.destroy
    respond_to do |format|
      format.html { redirect_to beasts_url, notice: 'Bestia została usunięta' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beast
      @beast = Beast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beast_params
      params.require(:beast).permit(:firstname, :lastname, :pseudo, :degree, :rating, :bio, :image, :subject_ids => [])
    end
end

app/helpers/beasts_helper.rb
module BeastsHelper
end

app/views/beasts/_form.html.erb
<%= simple_form_for(beast) do |form| %>
  <% if beast.errors.any? %>
    <div id="error_explanation">
      <h2>Wystąpily następujące błędy</h2>

      <ul>
        <% beast.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :zdjęcie %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :imię %> <br>
    <%= form.text_field :firstname, id: :beast_firstname %>
  </div>

  <div class="field">
    <%= form.label :nazwisko %> <br>
    <%= form.text_field :lastname, id: :beast_lastname %>
  </div>

  <div class="field">
    <%= form.label :pseudo %> <br>
    <%= form.text_field :pseudo, id: :beast_pseudo %>
  </div>

  <div class="field">
    <%= form.label :stopień %> <br>
    <%= form.select :degree, ['mgr', 'dr', 'dr hab.', 'prof.'], id: :beast_degree %>
  </div>

  <div class="field">
    <%= form.label :opis %> <br>
    <%= form.text_area :bio, id: :beast_bio %>
  </div>

  <%= form.label :prowadzone_przedmioty %>
  <%= form.association :subjects, :label => false, :as => :check_boxes, :item_wrapper_tag => :div %>

  <div class="actions">
    <%= form.button :submit , "Zapisz" %>
  </div>
<% end %>

app/views/beasts/edit.html.erb
<h1>Popraw dane Bestii</h1>

<%= render 'form', beast: @beast %>


<hr class="my-4">


<%= link_to 'Pokaż', @beast %> |
<%= link_to 'Powrót', beasts_path %>

app/views/beasts/index.html.erb
<% if current_user.role == "admin" %>
  <%= link_to 'Dodaj nową bestię', new_beast_path, :class => "btn btn-lg btn-secondary pull-right" %>
<% end %>

<h1>Spis bestii</h1>

<table class="table">
  <thead>
  <tr>
    <th>Stopień</th>
    <th>Imię</th>
    <th>Nazwisko</th>
    <th>Pseudo</th>
    <th>Ocena</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @beasts.each do |beast| %>
    <tr>
      <td><%= beast.degree %></td>
      <td><%= beast.firstname %></td>
      <td><%= beast.lastname %></td>
      <td><%= beast.pseudo %></td>
      <td><%= beast.rating.round(2) %></td>
      <td><%= link_to 'Pokaż', beast, :class => "navigation-link" %></td>
      <% if can? :manage, beast %>
        <td><%= link_to 'Edytuj', edit_beast_path(beast), :class => "navigation-link" %></td>
        <td><%= link_to 'Usuń', beast, method: :delete, data: {confirm: 'Na pewno chcesz usunąć te bestie?'}, :class => "navigation-link" %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/beasts/new.html.erb
<h1>Dodaj nową bestię</h1>

<%= render 'form', beast: @beast %>


<hr class="my-4">


<%= link_to 'Powrót', beasts_path %>

app/views/beasts/show.html.erb
<% if notice %>
  <div class="alert alert-success">
    <div class="notice">
      <%= notice %>
    </div>
  </div>
<% end %>




<div class="jumbotron">

  <div class="beast-card">
    <% if @beast.image.attached? %>
      <%= image_tag(@beast.image, :class => "beast-photo") %>
    <% else %>
      <h3>brak obrazka</h3>
    <% end %>
    <div class="beast-info">
      <h1 class="display-3 align-content-center"><%= @beast.degree %> <%= @beast.firstname %> <%= @beast.lastname %></h1>
      <% if @beast.pseudo != "" %>
        <h1>( <%=  @beast.pseudo  %> )</h1>
      <%  end %>
      <h4>Ocena użytkowników: <%= @beast.rating.round(2) %></h4>
    </div>
  </div>
  <hr class="my-4">
  <h4>Przedmioty</h4>
  <% @beast.subjects.each do |s| %>
    <p class="badge badge-secondary">
      <%= link_to s.name, '/subjects/'+s.id.to_s %>
    </p>
  <% end %>
  <hr class="my-4">
  <p> <%= @beast.bio %> </p>
</div>



<h2 class="display-3">Opinie</h2>
<h4 class="display-5"> Dodaj swoją opinię </h4>
<%= simple_form_for([@beast, @beast.comments.new]) do |f| %>

  <div class="row">
    <div class="form-group col-md-1">
      <%= f.label :ocena %><br/>
      <%= f.number_field :rate, autofocus: true, class: "form-control", in: 1.0..10.0 %>
    </div>

    <div class="form-group col-md-11">
      <%= f.label :Opinia %><br/>
      <%= f.text_field :message, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Dodaj" %>
  </div>
<% end %>
<div>
  <%= render partial: "/comment", collection: @beast.comments.reverse %>
</div>

<hr class="my-4">

<div class="center">
<% if can? :update, @beast %>
  <%= link_to 'Edytuj', edit_beast_path(@beast) %> |
<% end %>
<%= link_to 'Powrót', beasts_path %>
</div>