config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subjects do
    resources :comments, shallow: true
  end
  resources :users
  resources :beasts do
    resources :comments, shallow: true
  end

  root 'main#index'

end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :comments
  has_and_belongs_to_many :beasts

  validates :name, presence: true, length: {minimum: 2, maximum: 255}, uniqueness: true
  validates_inclusion_of :ects, :in => 1..10
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource


  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)
    @subject.rating = 0

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Przedmiot został dodany' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Zmiany zostały zapisane' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Przedmiot został usunięty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :ects, :description, :rating, :beast_ids => [])
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= simple_form_for(subject) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2>Wystąpiły następujące błędy</h2>

      <ul>
        <% subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-8">
      <%= form.label :nazwa %><br/>
      <%= form.text_field :name, id: :subject_name %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-8">
      <%= form.label :ects %><br/>
      <%= form.number_field :ects, id: :subject_ects %>
    </div>
  </div>


  <div class="row">
    <div class="form-group col-md-8">
      <%= form.label :opis %><br/>
      <%= form.text_area :description, id: :subject_description %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-8">
      <%= form.label :prowadzący %><br/>
      <%= form.association :beasts, :label => false, :as => :check_boxes, :item_wrapper_tag => :div %>
    </div>
  </div>

  <div class="actions">
    <%= form.button :submit , "Zapisz" %>
  </div>

<% end %>

app/views/subjects/edit.html.erb
<h1>Edytowanie przedmiotu</h1>

<%= render 'form', subject: @subject %>


<hr class="my-4">


<%= link_to 'Pokaż', @subject %> |
<%= link_to 'Powrót', subjects_path %>

app/views/subjects/index.html.erb
<% if current_user.role == "admin" %>
  <%= link_to 'Dodaj nowy przedmiot', new_subject_path, :class => "btn btn-lg btn-secondary pull-right" %>
<% end %>

<h1>Spis przedmiotów</h1>


<table class="table">
  <thead>
  <tr>
    <th>Nazwa</th>
    <th>Ects</th>
    <th>Ocena</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.name %></td>
      <td><%= subject.ects %></td>
      <td><%= subject.rating %></td>
      <td><%= link_to 'Pokaż', subject %></td>
      <% if can? :update, subject %>
        <td><%= link_to 'Edytuj', edit_subject_path(subject) %></td>
        <td><%= link_to 'Usuń', subject, method: :delete, data: {confirm: 'Na pewno?'} %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/subjects/new.html.erb
<h1>Dodaj nowy przedmiot</h1>

<%= render 'form', subject: @subject %>


<hr class="my-4">


<%= link_to 'Powrót', subjects_path %>

app/views/subjects/show.html.erb
<% if notice %>
  <div class="alert alert-success">
    <div class="notice">
      <%= notice %>
    </div>
  </div>
<% end %>


<div class="jumbotron">
  <h1 class="display-3"><%= @subject.name %></h1>
  <p class="lead"><%= @subject.ects %> ECTS, Ocena użytkowników: <%= @subject.rating %></p>
  <hr class="my-4">
  <h4>Prowadzący</h4>
  <% @subject.beasts.each do |beast| %>
    <p class="badge badge-secondary">
      <%= link_to "#{beast.degree} #{beast.firstname} #{beast.lastname}", "/beasts/#{beast.id.to_s}" %>
    </p>
  <% end %>
  <hr class="my-4">
  <p><%= @subject.description %></p>
</div>



<h2 class="display-3">Opinie</h2>
<h4 class="display-5"> Dodaj swoją opinię </h4>
<%= simple_form_for([@subject, @subject.comments.new]) do |f| %>

  <div class="row">
    <div class="form-group col-md-1">
      <%= f.label :ocena %><br/>
      <%= f.number_field :rate, autofocus: true, class: "form-control", in: 1.0..10.0 %>
    </div>

    <div class="form-group col-md-11">
      <%= f.label :Opinia %><br/>
      <%= f.text_field :message, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Dodaj" %>
  </div>
<% end %>
<div>
  <%= render partial: "/comment", collection: @subject.comments.reverse %>
</div>

<hr class="my-4">

<% if can? :update, @subject %>
  <%= link_to 'Edytuj', edit_subject_path(@subject) %> |
<% end %>
<%= link_to 'Powrót', subjects_path %>